### ISSUE TITLE
DSMR Injector compileren

### ISSUE THREAD

**Issue by fluppie** [mrWheel/DSMRinjector#2]
Hi @mrWheel,

I tried compiling your code Arduino with 1.8  but did not succeed. Would flashing a precompiled bin file by you work?
I have an analog meter and a charging point that needs a P1 telegram to charge above the failsafe current of 6A.
There are working commercial solutions out there, but they are over 160 euro https://www.slimmedingen.nl/csp1-3-fase-p1-simulator-dsmr4.html?id=276276710
Would be nice if I could just write the current from my SDM230 RTU Modbus meter to this program and generate my own P1 signal.
If this code is not intended to be used, please let me know as well, then I need to think of something else.

**Comment by mrWheel** [comment]
@fluppie ,

This code is not intended to do that.

But it will be fairly simple to create code to just compose a telegram with minimal fields for your use-case.
